### ISSUE TITLE
Move the newsletter signup form

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-theme#12]
It's currently in the header, we want it to show up in the footer instead.

(design to come)

**Comment by misfist** [comment]
This can be done in the WP dashboard. 

http://tni-staging.positiondevapp.com/wp/wp-admin/widgets.php (MailChimp Sign-up form).

If you think it would be useful, I can add another footer widget.

As a note, the current form doesn't work because the design called for 1 single field, which the actual MailChimp list (created on mailchimp.com) has additional required fields.

Email Address* | EMAIL | email
Full Name*  |  FNAME | text
Your City/Town* | MMERGE2 | text 

Either the Mailchimp list needs to be modified to only require email or the form on the site needs to be changed.

**Comment by frnsys** [comment]
Yeah I think we should have a separate footer widget for the newsletter, to manage/style it separately from the copyright info.

I tried signing up with the form yesterday and it seemed to work, strangely...I will try again.

**Comment by frnsys** [comment]
@misfist Trying to see if we can just use the existing Copyright part: I've dragged the newsletter widget from the Header widgets to the Copyright part, but the html that's produced is different than when it is in the header, e.g. there is no container with class `widget_mc4wp_form_widget` or a title element with class `widget-title`. I can't figure out why that is?

**Comment by misfist** [comment]
When sidebars (widget areas) are registered, there are settings that include markup for the container and widget title. 

All header and footer sidebars can be modified to have consistent markup. Do you have any preference for what this would look like?

**Comment by misfist** [comment]
For reference, this is where the sidebars are registered. 

https://github.com/misfist/tni-theme/blob/master/inc/setup.php#L13-L33

I made the copyright widget markup different because, based on the designs, I didn't think it would be used as a flexible, multi-use area.

Adding a general footer widget area would probably be the best solution.

https://github.com/misfist/tni-theme/pull/16

**Comment by frnsys** [comment]
Styling for this is handled in 8d5d68aefd63b97df0e7fc59647f5ab52db30a83. Staging site isn't updated yet but will setup the widget when we deploy the latest changes
